### ISSUE TITLE
关于刷题

### ISSUE THREAD

**Issue by wangrenfeng0** [emma-data-works/ds-class-intro#18]
您在视频里说到刷题，我想请问Emma，如果我不想去湾区和西雅图的科技公司，只想在DFW local找个银行或者普通公司的DS职位，请问还要刷题吗？比如citi, santander和comerica bank，招人好像很松的样子，虽然公司不怎么样，比不上chase, capital one或者Toyota，以上那些公司需要刷题吗？

**Comment by emma-data-works** [comment]
我猜不用，还在用SAS的公司应该都不用的~ 可以在glassdoor上看看他们都面些什么~

**Comment by wangrenfeng0** [comment]
谢谢解答
