### ISSUE TITLE
A/B Testing的一些问题

### ISSUE THREAD

**Issue by wangrenfeng0** [emma-data-works/ds-class-intro#19]
1. 请问health industry是不是基于ethic问题，不会去做A/B Test?同时也是因为health study都是observation study，不是randomize？
2. A/B testing是不是只要对当前的sample data randomize到control 和treatment group后产生causal inference即可算达成目标？无需inference to the population? 换而言之，对于用于A/B testing的sample data需要randomly selected from population吗？
3. A/B testing是不是基于additive model的？即像您视频里说的，不能有任何interaction？
4. 视频2：01：00讲到了不能任意增加sample size，会导致false positive. 如果我的sample size过小，testing达不到我期待的power，比如0.8，那我是不是需要等到未来有足够多的sample的时候再说？因为现在做的A/B testing 所得到的result没有意义？
5. 视频里说到long-term和short-term metrics，我想问下这里涉不涉及到repeat mesaure里的Longitudinal study？如果涉及到，那repeat measure对A/B testing有什么影响？

**Comment by emma-data-works** [comment]
> 请问health industry是不是基于ethic问题，不会去做A/B Test?同时也是因为health study都是observation study，不是randomize

clinical trial/medical research除了ethics，更多的是小样本，需要control for patient condition(age, existing condition, etc.)，还有一些追踪效果的难度。会需要更复杂和考虑更多因素的实验设计才能用统计方法读出结果。主要原因不是ethics，因为clinical trial也会有双盲随机。

> A/B testing是不是只要对当前的sample data randomize到control 和treatment group后产生causal inference即可算达成目标？无需inference to the population? 换而言之，对于用于A/B testing的sample data需要randomly selected from population吗？

好问题，因为太常用了所以我忘记在视频里讲，A/B都需要尽量是是population的一个representative random sample。不能generalize到最后实用场景的test是没有实际意义的

> A/B testing是不是基于additive model的？即像您视频里说的，不能有任何interaction？

简单的A/B testing只是测试independent sample mean，如果认为有interaction可能会因为[Simpson's paradox](https://towardsdatascience.com/what-is-simpsons-paradox-4a53cd4e9ee2)导致误读

> 视频2：01：00讲到了不能任意增加sample size，会导致false positive. 如果我的sample size过小，testing达不到我期待的power，比如0.8，那我是不是需要等到未来有足够多的sample的时候再说？因为现在做的A/B testing 所得到的result没有意义？

是，但sample size一般是实验设计的时候算出来的，sample size和实验长度设计都是事先定好的。如果一开始就知道达不到sample size，实验结果没有意义，可以不用做，或者调整一些假设和实验精度

> 视频里说到long-term和short-term metrics，我想问下这里涉不涉及到repeat mesaure里的Longitudinal study？如果涉及到，那repeat measure对A/B testing有什么影响？

我这里说的更偏向于business长期和短期的metrics，比如实验虽然能带来短期的流量，但长期可能churn更多，还不如之前的方案，类似这种。 Repeated measure得到的sample有correlation，[可能会影响结论](https://web.stanford.edu/~kcobb/hrp259/correlateddata.pdf)，应该用合适的方法去adjust variance estimate或者用更合适的实验方法，而不是简单A/B

**Comment by wangrenfeng0** [comment]
谢谢，你给的两个链接我会好好看下
