### ISSUE TITLE
怎样提高Regex搜索技能？

### ISSUE THREAD

**Issue by wangrenfeng0** [emma-data-works/ds-class-intro#2]
我发现自己在使用API text mining的时候，因为regex基础没有打牢，所以经常要尝试各种字符来trial and error自己想要检索的内容，请问怎么练习提高regex？哪些是常用的？面试的时候考的多不多？比如home work exercise 3那道题，面试时候会的人很快能写出来，不熟练的会卡很久。

**Comment by emma-data-works** [comment]
这是好问题，regex真的东西比较杂又是case by case，所以我也都是用的时候才去查，不过对于基本的结构有了解需要用的时候能查得到就可以啦。还有就是build your own code library，对于做过的东西随手写一写注释，对于以后有可能会反复用到的东西整理一下备用

我个人觉得general DS面试的时候考到regex的概率其实不是很大，不确定做NLP的岗位会不会问，毕竟处理数据可能会用到

一些也许有帮助的资源（有教程也可以直接帮你complie）
https://regex101.com/
https://www.rexegg.com/

**Comment by wangrenfeng0** [comment]
谢谢emma解答，有些简单的technical问题我留到周日答疑时候再问
