### ISSUE TITLE
print(name, end)有点问题

### ISSUE THREAD

**Issue by wangrenfeng0** [emma-data-works/ds-class-intro#8]
视频47：30的时候，print(name, end)这里有点问题。我觉得是同时print name和end两个字符串，然后中间用default的空格隔开，print function里面的value如果不指定sep或者end的话，会默认是连续几个value以sep=default的形式print出来。而不是视频里面说的以end为第二个默认的字符赋值给sep

**Comment by emma-data-works** [comment]
谢谢同学的comment，你说的是对的，这里不是默认`end='!'`而是两个value并列，中间由空格隔开一起打印出来，谢谢你指出

**Comment by wangrenfeng0** [comment]
谢谢
